### PR TITLE
Cookie should also be set on the extractRange request

### PR DESCRIPTION
**Pull request by simb0**
Little fix for requests that needs some cookies ;)

### CODE REVIEW

**Comment by axet** [comment]
seems reasonable. thank you

**Comment by axet** [comment]
But wait. It already been done using UrlInfo.openConnection() doesn't it?

**Comment by simb0** [comment]
You are right... it should but it doesn't. Let me dig into my testcase and i will finger it out.

**Comment by simb0** [comment]
Okay, the cookie is not set because it's null. And it's null because it's only set in the meta function. So the extractRange function never has an cookie. It's possible to set the cookie in the extractRange function first line url.setCookie(cookie); or in the download(URLInfo url) function right before extractRange is called.

What do you think?

**Comment by axet** [comment]
meta() function maintain has two connections, first before redirect, second after it. so remote side can now it is the same remote user - we keep cookie.

extractRange - first and only one connection, remote server cannot possible have any information about us, expect if you fill it manually.

**Comment by simb0** [comment]
Okay understand it, in my case i set the cookie manually. Idea behind this is that a need to login before i can download. So i do a login, save the cooke from the response, and set this cookie in URLinfo.

So it would be great if extractRange can set my cookie too ;)

` // if range failed - do plain download with no retrys's
    protected HttpURLConnection extractRange(URLInfo url) throws IOException {
        //set cookie
        url.setCookie(cookie);

        HttpURLConnection conn = url.openConnection();

        // may raise an exception if not supported by server
        conn.setRequestProperty("Range", "bytes=" + 0 + "-" + 0);`

**Comment by axet** [comment]
It does. Check again.

**Comment by simb0** [comment]
Unfortunately not :(

Just checked it with ExampleApplicationManaged, only changed the download url + info.setCookie(myCookie) in the main(). 

The outcome is an exception
```
EXTRACTING
Exception in thread "main" java.lang.RuntimeException: Server does not support RANGE, cant set multipart
	at com.github.axet.wget.info.DownloadInfo.enableMultipart(DownloadInfo.java:223)
	at com.github.axet.wget.info.DownloadInfo.enableMultipart(DownloadInfo.java:215)
	at com.github.axet.wget.ExampleApplicationManaged.main(ExampleApplicationManaged.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
EXTRACTING_DONE:
```

**Comment by axet** [comment]
Try wget-1.4.9

**Comment by simb0** [comment]
Thank you, with 1.4.9 it work very well ;) Another question: It would be nice if the multipart download can be resumable. Do you plan something like that?

**Comment by axet** [comment]
it requires to keep download state somewhere. so, it can be done only by application. just save it next to file you are downloading and you will be fine.

**Pull request closed without merging**
